# To avoid cache key collisions, define every cache keys in this file
# Cache time should be in seconds

HOME_PINNED_TOPICS = 'HOME_PINNED_TOPICS'
HOME_PINNED_TOPICS_CACHE_TIME = 60 * 60

HOME_RECENT_POSTS = 'HOME_RECENT_POSTS'
HOME_RECENT_POSTS_CACHE_TIME = 5 * 60

HOME_COMING_CONTESTS = 'HOME_COMING_CONTESTS'
HOME_COMING_CONTESTS_CACHE_TIME = 60 * 60

HOME_CONTRIBUTORS = 'HOME_CONTRIBUTORS'
HOME_CONTRIBUTORS_CACHE_TIME = 60 * 60